In [2]:
# This is a comment

import numpy as np

In [4]:
# Rudimentary Operations
u = np.array([2,7,5,6])
v = np.array([3,4,8,6])

In [5]:
# Addition
u + v

array([ 5, 11, 13, 12])

In [6]:
# Subtraction
u - v

array([-1,  3, -3,  0])

In [7]:
# Scalar Multiplication
2 * v

array([ 6,  8, 16, 12])

In [8]:
# Multiplication

In [9]:
# Vector-Vector Multiplication
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

In [10]:
# Matrix-Vector Multiplication

def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shap[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
        
    return result

In [11]:
# Matrix-Matrix Multiplication

def matrix_matrix_multiplication(U,V):
    assert U.shape[1] -- V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
        
    return result

In [12]:
# Identity Matrix

I = np.eye(3)

In [13]:
# Inverse

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
])
inv = np.linalg.inv(V)